[all]
master01 ansible_host=192.168.254.201 ansible_user=mcbtaguiad
master02 ansible_host=192.168.254.202 ansible_user=mcbtaguiad
master03 ansible_host=192.168.254.203 ansible_user=mcbtaguiad
; worker01 ansible_host=192.168.254.204 ansible_user=mcbtaguiad
; worker02 ansible_host=192.168.254.205 ansible_user=mcbtaguiad

[master]
master01 ansible_host=192.168.254.201 ansible_user=mcbtaguiad
master02 ansible_host=192.168.254.202 ansible_user=mcbtaguiad
master03 ansible_host=192.168.254.203 ansible_user=mcbtaguiad

; [worker]
; worker01 ansible_host=192.168.254.204 ansible_user=mcbtaguiad
; worker02 ansible_host=192.168.254.205 ansible_user=mcbtaguiad
