---
- name: Apply Cluster Role
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/standard/cluster-role.yaml
    kubeconfig: "{{ KUBECONFIG }}"
  run_once: true
  delegate_to: "{{ groups['master'][0] }}"
# ============================================================================ #
- name: Apply Cluster Role Binding
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/standard/cluster-role-binding.yaml
    kubeconfig: "{{ KUBECONFIG }}"
  run_once: true
  delegate_to: "{{ groups['master'][0] }}"
# ============================================================================ #
- name: Apply Service Account
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/standard/service-account.yaml
    kubeconfig: "{{ KUBECONFIG }}"
  run_once: true
  delegate_to: "{{ groups['master'][0] }}"
# ============================================================================ #
- name: Apply Deployment
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/standard/deployment.yaml
    kubeconfig: "{{ KUBECONFIG }}"
  run_once: true
  delegate_to: "{{ groups['master'][0] }}"
# ============================================================================ #
- name: Apply Service
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/standard/service.yaml
    kubeconfig: "{{ KUBECONFIG }}"
  run_once: true
  delegate_to: "{{ groups['master'][0] }}"

