
# ============================================================================ #
# Author: Mark Taguiad <marktaguiad@tagsdev.xyz>
# ============================================================================ #
- hosts: all
  become: true
  vars:
    HOST_COUNT: "{{ ansible_play_hosts | length }}"
    MASTER_IP: "{{ hostvars['master1']['ansible_default_ipv4']['address'] }}"
# ============================================================================ #
  tasks:
  - name: Get swap disk
    shell: |-
      fdisk -l | grep swap | awk '{ print $1 }' | sed 's/\://' 
    register: SWAP_DISK
  # - name: Get UUID
  #   shell: |-
  #     blkid {{SWAP_FS.stdout}} | awk '{ print $2}'
  #   register: SWAP_UUID
  - name: Mount swap
    mount:
      src: "{{SWAP_DISK.stdout}}"
      path: swap
      fstype: swap
      opts: defaults
      state: present